#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BTDemo.Resource", IsApplication=true)]

namespace BTDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04001a
			public const int ble_connect = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int ble_getservices = 2130968603;
			
			// aapt resource value: 0x7f040019
			public const int ble_refresh = 2130968601;
			
			// aapt resource value: 0x7f040001
			public const int characteristics_back = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int characteristics_list = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int characteristics_refresh = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int characteristics_stepinto = 2130968579;
			
			// aapt resource value: 0x7f040017
			public const int choose_state = 2130968599;
			
			// aapt resource value: 0x7f040010
			public const int device_addr = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int device_bond_state = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int device_choose_state = 2130968595;
			
			// aapt resource value: 0x7f040018
			public const int device_list = 2130968600;
			
			// aapt resource value: 0x7f04000f
			public const int device_name = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int device_type = 2130968593;
			
			// aapt resource value: 0x7f040005
			public const int service_back = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int service_characteristics = 2130968597;
			
			// aapt resource value: 0x7f040004
			public const int service_list = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int service_refresh = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int service_stepinto = 2130968583;
			
			// aapt resource value: 0x7f040016
			public const int service_type = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int service_uuid = 2130968596;
			
			// aapt resource value: 0x7f040008
			public const int settings_back = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int settings_regist_char_notify = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int settings_set_value = 2130968588;
			
			// aapt resource value: 0x7f04000e
			public const int settings_unregist_char_notify = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int settings_value_hex = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int settings_value_input = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int settings_value_str = 2130968586;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int activity_characteristics = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int activity_service = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int activity_set_characteristic_value = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int item_device = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int item_service = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Main = 2130837509;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int connect_ble = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
